#ifndef INCLUDED_memory_config_H
#define INCLUDED_memory_config_H

#define LG_BACKGROUND_TILES_SIZE 128
#define LG_ART_SQUARE_SIZE 32
#define LG_TILES_PER_SQUARE (LG_BACKGROUND_TILES_SIZE / LG_ART_SQUARE_SIZE)
#define LG_TILES_OFFSET 0
#define LG_MAP_OFFSET 20
#define LG_OVERLAY_LAYER_BASE 4
#define LG_OVERLAY_LAYER_BASE_SUB 0

#endif
