#ifndef LG_INCLUDED_techtree_H
#define LG_INCLUDED_techtree_H

// THIS FILE IS GENERATED BY BUILDTT.PL

#include <nds/jtypes.h>

enum Technology
{
	Tech_Invalid = -1,
	Tech_Farming,
	Tech_Wheel,
	Tech_Animal__Husbandry,
	Tech_Agriculture,
	Tech_Masonry,
	Tech_Mining,
	Tech_Metal_Work,
	Tech_Irrigation,
	Tech_Machinery,
	Tech_Fossil_Fuels,
	Tech_Mathematics,
	Tech_Alphabet,
	Tech_Maps,
	Tech_Compass,
	Tech_War_Boats,
	Tech_Construction,
	Tech_Engineering,
	Tech_Currency,
	Tech_Trade_Routes,
	Tech_Education,
	Tech_Religion,
	Tech_Medicine,
	Tech_Fusion,
	Tech_Advanced_Construction,
	Tech_Tornado__Resistance,
	Tech_Count
};

struct TechnologyInfo
{
	const char* name;
	const char* result;
	u16 cost;
	u16 screenX, screenY;
	u16 width, height;
	Technology dependents[4];
};

extern const TechnologyInfo gTechInfo[];

#define LG_TECHTREE_BITMAP_WIDTH 512
#define LG_TECHTREE_BITMAP_HEIGHT 256

#endif
